### ISSUE TITLE
False negatives

### ISSUE THREAD

**Issue by Sora2455** [superhuman/rxxr2#11]
I ran the entire list of know bad regexes from https://en.wikipedia.org/wiki/ReDoS#Malicious_regexes into https://regex.rip, and they all came back as non-vulnerable.

Examples:
- (a+)+
- ([a-zA-Z]+)*
- (a|aa)+
- (a|a?)+

**Comment by ConradIrwin** [comment]
Hey @Sora2455, thanks for reporting!

These examples are actually not vulnerable regular expressions when run by themselves because there's nothing that will trigger the engine to start backtracking.

The easiest was to trigger backtracking is to add is `$` – this only matches the end of the string, and not `a`, but you could add any character here (e.g. `b` too).

e.g.
```javascript
n = performance.now(); /(a+)+/.test('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!'); console.log(performance.now() - n)
// => 0.02 ms
n = performance.now(); /(a+)+$/.test('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!'); console.log(performance.now() - n)
// => 115597.13 ms
```

And regexp.rip identifies `/(a+)+/` as not vulnerable, but `/(a+)+$/` as vulnerable.

It looks like the article is missing the third criteria for a malicious regex which is that there is a portion of the regex after the repeated section that does not match the repeated section. I've updated the Wikipedia page to help avoid this confusion in the future: https://en.wikipedia.org/w/index.php?title=ReDoS&type=revision&diff=962808344&oldid=919530334
