### ISSUE TITLE
Regexp from OWASP are not considered vulnerable while they are

### ISSUE THREAD

**Issue by KevinGuancheDarias** [superhuman/rxxr2#42]
Hello, I have tested this program with the OWASP known examples, and it doesn't display them as vulnerable

![image](https://user-images.githubusercontent.com/6832422/209971095-4a33b6e0-cb0c-411e-8fec-d57b80502dc8.png)

Also to those willing to use the Dockerfile (so not having to install anything in the computer), i modified the Dockerfile
```dockerfile
FROM ocaml/opam2

RUN sudo apt-get install m4 --yes
RUN opam update
RUN opam install dune cohttp cohttp-lwt-unix lwt yojson
ADD --chown=opam code /home/opam/code
RUN cd /home/opam/code; eval $(opam env); dune build http.exe
ENTRYPOINT ["/home/opam/code/_build/default/http.exe"]

```

Run the generated image with `docker run -d -p 8082:8181 246c4689a59e`

**Comment by ConradIrwin** [comment]
This regex is not vulnerable by itself (though it is a common pattern that contributes to a regex being vulnerable).

A vulnerable regex consists of two parts, A and B, where A can match a substring in an exponential number of ways, and B does not match the same set of strings that A does. The example here is just an A part. You can construct a vulnerable regex by adding a B part that does not match the same set of strings as the A part, for example: /([a-zA-Z]+)*1/ is vulnerable because when matched against a long string of alphabet characters containing no 1s, it will backtrack exponentially.
